name: Build
run-name: ${{ github.actor }} is pushing tag to repository

on:
  push:
    tags:
      - rc-0.0.[0-9]+

jobs:
  test-and-lint:
    uses: ./.github/workflows/ci-test-lint.yml

  build:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create docker image
        run: docker build . -t ${{ github.ref_name }}
      - name: Send release information to tracker
        uses: ./.github/actions/send-to-tracker
        with:
          oauth-token: ${{ secrets.YANDEX_OAUTH_TOKEN }}
          org-id: ${{ secrets.YANDEX_TRACKER_ID }}
          ticket-id: ${{ secrets.YANDEX_TICKET_ID }}
          tag: ${{ github.ref_name }}
